# Generated by Django 5.2.4 on 2025-07-17 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Politikai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='govener_profile_pics/')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('country_of_origin', models.CharField(max_length=50)),
                ('biography', models.TextField(max_length=1000)),
                ('political_party', models.CharField(max_length=100)),
                ('political_past', models.TextField(max_length=1000)),
                ('political_opinion', models.TextField(max_length=1000)),
                ('millitery_rank', models.CharField(max_length=100)),
                ('millitery_past', models.TextField(max_length=500)),
                ('education', models.TextField(max_length=500)),
                ('way_of_living', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Goverment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('party_ceo_or_secretary_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_ceo_or_secretary_general', to='vapp.politikai')),
                ('party_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_leader', to='vapp.politikai')),
                ('party_member_eight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_member_eight', to='vapp.politikai')),
                ('party_member_eleven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_member_eleven', to='vapp.politikai')),
                ('party_member_five', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_member_five', to='vapp.politikai')),
                ('party_member_four', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_member_four', to='vapp.politikai')),
                ('party_member_fourteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_member_fourteen', to='vapp.politikai')),
                ('party_member_nine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_member_nine', to='vapp.politikai')),
                ('party_member_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_member_one', to='vapp.politikai')),
                ('party_member_seven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_member_seven', to='vapp.politikai')),
                ('party_member_six', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_member_six', to='vapp.politikai')),
                ('party_member_ten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_member_ten', to='vapp.politikai')),
                ('party_member_thirteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_member_thirteen', to='vapp.politikai')),
                ('party_member_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_member_three', to='vapp.politikai')),
                ('party_member_twelve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_member_twelve', to='vapp.politikai')),
                ('party_member_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_member_two', to='vapp.politikai')),
                ('party_spokesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_spokesperson', to='vapp.politikai')),
                ('regional_activists_or_branch_leaders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_activists_or_branch_leaders', to='vapp.politikai')),
                ('strategic_advisor_or_campaign_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_advisor_or_campaign_manager', to='vapp.politikai')),
                ('treasurer_or_finance_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasurer_or_finance_manager', to='vapp.politikai')),
            ],
        ),
    ]
