# Generated by Django 5.2.4 on 2025-07-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='politikai',
            old_name='way_of_living',
            new_name='career',
        ),
        migrations.RenameField(
            model_name='politikai',
            old_name='name',
            new_name='first_name',
        ),
    ]
