# Generated by Django 5.2.4 on 2025-07-17 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0002_rename_way_of_living_politikai_career_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goverment',
            name='party_member_eighteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_member_eighteen', to='vapp.politikai'),
        ),
        migrations.AddField(
            model_name='goverment',
            name='party_member_fifteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_member_fifteen', to='vapp.politikai'),
        ),
        migrations.AddField(
            model_name='goverment',
            name='party_member_nineteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_member_nineteen', to='vapp.politikai'),
        ),
        migrations.AddField(
            model_name='goverment',
            name='party_member_seventeen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_member_seventeen', to='vapp.politikai'),
        ),
        migrations.AddField(
            model_name='goverment',
            name='party_member_sixteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_member_sixteen', to='vapp.politikai'),
        ),
        migrations.AddField(
            model_name='goverment',
            name='party_member_twenty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_member_twenty', to='vapp.politikai'),
        ),
        migrations.AlterField(
            model_name='goverment',
            name='party_member_eight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_member_eight', to='vapp.politikai'),
        ),
        migrations.AlterField(
            model_name='goverment',
            name='party_member_eleven',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_member_eleven', to='vapp.politikai'),
        ),
        migrations.AlterField(
            model_name='goverment',
            name='party_member_five',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_member_five', to='vapp.politikai'),
        ),
        migrations.AlterField(
            model_name='goverment',
            name='party_member_four',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_member_four', to='vapp.politikai'),
        ),
        migrations.AlterField(
            model_name='goverment',
            name='party_member_fourteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_member_fourteen', to='vapp.politikai'),
        ),
        migrations.AlterField(
            model_name='goverment',
            name='party_member_nine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_member_nine', to='vapp.politikai'),
        ),
        migrations.AlterField(
            model_name='goverment',
            name='party_member_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_member_one', to='vapp.politikai'),
        ),
        migrations.AlterField(
            model_name='goverment',
            name='party_member_seven',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_member_seven', to='vapp.politikai'),
        ),
        migrations.AlterField(
            model_name='goverment',
            name='party_member_six',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_member_six', to='vapp.politikai'),
        ),
        migrations.AlterField(
            model_name='goverment',
            name='party_member_ten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_member_ten', to='vapp.politikai'),
        ),
        migrations.AlterField(
            model_name='goverment',
            name='party_member_thirteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_member_thirteen', to='vapp.politikai'),
        ),
        migrations.AlterField(
            model_name='goverment',
            name='party_member_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_member_three', to='vapp.politikai'),
        ),
        migrations.AlterField(
            model_name='goverment',
            name='party_member_twelve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_member_twelve', to='vapp.politikai'),
        ),
        migrations.AlterField(
            model_name='goverment',
            name='party_member_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_member_two', to='vapp.politikai'),
        ),
    ]
