# Generated by Django 5.2.4 on 2025-07-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0003_goverment_party_member_eighteen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politikai',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='govener_profile_pics/'),
        ),
    ]
